### ISSUE TITLE
[问题] 小概率无法复制完整文件

### ISSUE THREAD

**Issue by BailPlus** [BailPlus/deskcopy#7]
提交: 
发起人: @BailPlus 
发起时间: 2023.3.24 20:42

# 问题描述
有些文件体积较大，复制到桌面所需时间较长。若检测间隔时间过短，则可能导致不能复制完整文件的问题。
# 解决方案
暂无

**Comment by BailPlus** [comment]
(2023.3.24 20:45)
@Will-Plus : 初步解决方案：设置一个文件大小阈值，超过阈值则不予复制。

**Comment by Will-Plus** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在学校，无法亲自回复你的邮件。我将在假期开始后，尽快给你回复。

**Comment by BailPlus** [comment]
(2023.3.25 18:48)
@Will-Plus : 阈值大小为50MB为佳。还有，将检测时间延长为10s

**Comment by BailPlus** [comment]
(2023.3.25 19:09)
> @Will-Plus : 阈值大小为50MB为佳。还有，将检测时间延长为10s

但这不能完全解决问题。如果是10s的最后一秒开始向桌面复制大文件，则仍为残缺文件。
我认为，需要定时获取`~/Desktop`下所有文件大小，并与已有值进行对比。若不同，则开始复制。

**Comment by BailPlus** [comment]
已完成。提交: d4a33d9b3aef6262a18ce7a78bd1405cbca54854

**Comment by BailPlus** [comment]
(2023.3.25 19:14)
新逻辑
将比对文件数量(`len(os.listdir(...))`)改为比对文件大小。将所有文件大小放到一个列表中即可，不必区分文件。
# 获取逻辑
1. 使用`os.walk(...)`找出所有非目录文件，放入列表1
2. 遍历列表1，获取每个文件大小，放入列表2。
3. 列表2即为即为下述“新列表”。
# 比对逻辑 (参数: 旧列表,新列表)
1. 先比对列表长度，若长度不等则跳过后续步骤，直接启动复制。
2. 遍历新列表，寻找旧列表中有无相等的值。只要有一个值不同，停止比对，启动复制。
# 注意事项
1. 获取文件大小时不必排除`.lnk`文件。
2. 比对间隔为@Will-Plus 提供的10s
3. 获取文件大小方法尚不明确，需要近期学习。

**Comment by BailPlus** [comment]
(2023.3.28 14:46)
昨已将间隔时间延长为30s

**Comment by BailPlus** [comment]
(2023.3.28 14:46)
昨已将间隔时间延长为30s

**Comment by BailPlus** [comment]
已完成。提交: d4a33d9b3aef6262a18ce7a78bd1405cbca54854

**Comment by BailPlus** [comment]
(2023.3.28 15:03)
昨天下午看了下Python参考书，学到了获取文件大小的方法。
```python
size = __import__('os').start(<filename>).st_size
```
单位: 字节; 类型: `int`

**Comment by BailPlus** [comment]
(2023.4.9 11:44)
> @Will-Plus : 初步解决方案：设置一个文件大小阈值，超过阈值则不予复制。

已拒绝阈值方案。原因：
1. 比对文件大小方案已可以解决此问题。
2. 设置阈值后可能会复制不到一些大体积课件。如：
    - 美术 《写生与创作》
    - 物理 分子热运动系列

**Comment by BailPlus** [comment]
已完成。提交: d4a33d9b3aef6262a18ce7a78bd1405cbca54854
